"""
sin.agent.packet
════════════════
High-performance packet anomaly receiver.
Listens on local UDP port 9999 for pre-digested threat signals
generated by the compiled Go pcap sniffer. Zero Python GIL overhead.
"""
import socket
import json
import threading
from typing import List, Dict
from sin.utils.logger import get_logger

logger = get_logger("sin.agent.packet")

class PacketEngine:
    def __init__(self, port: int = 9999):
        self.port = port
        self.signals: List[Dict] = []
        self._running = False
        self._lock = threading.Lock()
        
        # UDP Socket for receiving Go signals
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        # 1-second timeout so the thread can exit cleanly on stop()
        self.sock.settimeout(1.0) 
        
    def start_capture(self) -> None:
        """Starts the UDP listener to receive signals from the Go sniffer."""
        try:
            self.sock.bind(("127.0.0.1", self.port))
            logger.info(f"PacketEngine listening for Go sniffer signals on UDP {self.port}")
            self._running = True
        except Exception as e:
            logger.error(f"Failed to bind PacketEngine receiver: {e}")
            return

        while self._running:
            try:
                data, _ = self.sock.recvfrom(4096)
                signal = json.loads(data.decode('utf-8', errors='ignore'))
                
                with self._lock:
                    self.signals.append(signal)
            except socket.timeout:
                continue
            except json.JSONDecodeError:
                logger.warning("Received malformed JSON from Go sniffer")
            except Exception as e:
                if self._running:
                    logger.error(f"Packet receiver error: {e}")

    def drain_signals(self) -> List[Dict]:
        """Returns accumulated signals and clears the buffer."""
        with self._lock:
            current_signals = self.signals[:]
            self.signals.clear()
        return current_signals

    def stop(self) -> None:
        """Halts the receiver thread."""
        self._running = False
        try:
            self.sock.close()
        except Exception:
            pass
